export const paths = {
    login: "/auth/login",
    register: "/agent/register",
    mainAgentRegister: "/agent/main/register",
    subAgentRegister: "/agent/sub/register",
    verification: "/account/verification",
    resendCode: "/account/resend",
    forget_password: "/auth/forget-password",
    dashboard: "/dashboard",
    package: "/package",
    packageBuy: "/package/buy",
    bankAccount: "/bank-account",
    deposit: "/deposit",
    investorVerification: "/investor/account/verification",
    transcation: "/transcation",
    channel: "/channel",
    agent: "/agent",
    profile: "/profile",
}