export const paths = {
    agentLogin: "/auth/agent/login",
    register: "/agent/register",
    verification: "/account/verification",
    resendCode: "/account/resend",
    forget_password: "/auth/forget-password",
    dashboard: "/dashboard",
    package: "/package",
    packageBuy: "/package/buy",
    bankAccount: "/bank-account",
    investorVerification: "/investor/account/verification",
    transaction: "/transaction",
    deposit: "/deposit",
    channel: "/channel",
    agent: "/agent",
    profile: "/profile",
}